# Generated by Django 5.0.6 on 2024-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_rename_booked_on_booking_booked_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
